{% set name = "jesth" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jesth-{{ version }}.tar.gz
  sha256: 442fb5bb8b1a2a9306099384862737d6a31e30b73e109f7f2e1c194954ab5045

build:
  entry_points:
    - jesth = jesth.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - jesth
  commands:
    - pip check
    - jesth --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/jesth
  summary: Park and render Jesth notes which inherits properties from  the INI and TOML files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
